# Generated by Django 2.1.3 on 2018-12-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesignRecognition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='geotag',
        ),
        migrations.AddField(
            model_name='post',
            name='geo_latitude',
            field=models.FloatField(default=14.1059453, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='post',
            name='geo_longitude',
            field=models.FloatField(default=-87.2049887, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='agrees',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='correction',
            name='replace',
            field=models.CharField(choices=[('P', 'Persuasive'), ('N', 'Nudge'), ('H', 'Hostile')], max_length=1, null=True, verbose_name='Suggested Correction'),
        ),
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.TextField(max_length=280, null=True, verbose_name='Description'),
        ),
    ]
