# Generated by Django 2.1.3 on 2018-12-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesignRecognition', '0002_auto_20181201_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='geo_latitude',
            field=models.FloatField(default=14.1059453, max_length=50, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='post',
            name='geo_longitude',
            field=models.FloatField(default=-87.2049887, max_length=50, verbose_name='Longitude'),
        ),
    ]
